const list = [
  {
    "description": "The Men’s Staple Tank Top is made of high-quality durable materials. Wear it on a sunny day out or offer it to your customers on your online store.",
    "id": 1,
    "img_urlOne": "https://drive.google.com/uc?export=view&id=1oNJ0HPAAynGHwx0CiooJp5XK1RWFSzuq",
    "img_urlThree": "https://drive.google.com/uc?export=view&id=1vQbnOUvH8RGKK1ya0D_yQJPEGyMFE-G0",
    "img_urlTwo": "https://drive.google.com/uc?export=view&id=1vG-F0k8F7meag35KVn62xqIxpBbEpDFI",
    "name": " DD-214 Alumni tank Top",
    "price": 20,
    "amount": 1,
  },
  {
    "description": " Classic unisex hoodie with a front pouch pocket and matching flat drawstrings. The 100% cotton exterior makes this hoodie soft to the touch. What's more, if you go with custom prints, you can personalize the hoodie to your heart’s content and maximize your branding thanks to the custom inside label. Use it to showcase your logo, strengthen customer loyalty, and boost your brand’s visibility on the market. 65% ring-spun cotton, 35% polyester Charcoal Heather is 60% ring-spun cotton, 40% polyester Carbon Grey is 55% ring-spun cotton, 45% polyester 100% cotton face Fabric weight: 8.5 oz/yd² (288.2 g/m²) Front pouch pocket Self-fabric patch on the back Matching flat drawstrings 3-panel hoodTear-away tag",
    "id": 2,
    "img_urlOne": "https://drive.google.com/uc?export=view&id=1F1GgHfGhwWO7FPnFw-2hqzKSjbhq4YXp",
    "img_urlThree": "https://drive.google.com/uc?export=view&id=1EttW2F0alTMIbV0E33FxmdNCGJDlbqS7",
    "img_urlTwo": "https://drive.google.com/uc?export=view&id=1ExpL4ehLs9kwp9a3xbaAuGf8Rt2X_urd",
    "name": " DD-214 Alumni Hoodie",
    "price": 25,
    "amount": 1,
  },
  {
    "description": "This All-Over Print Premium Face Mask is made of two soft layers of polyester and has a pocket for a filter or napkin. The adjustable nose wire and elastic bands ensure a good fit. Complement the apparel in your online store by adding a unique design to this topical product!",
    "id": 3,
    "img_urlOne": "https://drive.google.com/uc?export=view&id=1En0viXreCa-PXktTs12CKvQkutUS9ri0",
    "img_urlThree": "https://drive.google.com/uc?export=view&id=1Em-sHJi8pFyt6ccltFZ_S9m4MPtf4hZq",
    "img_urlTwo": "https://drive.google.com/uc?export=view&id=1EsoLp3kaqeNm3dQ8VFfAU-YAIwtUOPKC",
    "name": " DD-214 Alumni Face Mask",
    "price": 15,
    "amount": 1,
  },
  {
    "description": "With your design, the Men's Classic T-Shirt will become a beloved go-to choice for any occasion. It has a boxy fit and is made from thick, pre-shrunk fabric, so the shirt maintains its shape even after multiple washes.",
    "id": 4,
    "img_urlOne": "https://drive.google.com/uc?export=view&id=1F6iOVame3rxSUZW-rzbKNSN7Uemw1wL3",
    "img_urlThree": "https://drive.google.com/uc?export=view&id=1F97Uv75VTCbxPe59tcjDJJel7GwIk5Id",
    "img_urlTwo": "https://drive.google.com/uc?export=view&id=1F2DOpDKd_M8utyz1TFKV6z4WW6QgXgcK",
    "name": " DD-214 Alumni T-Shirt",
    "price": 15,
    "amount": 1,
  },
  {
    "description": "The durable heavyweight fabric and soft inside make this Champion sweatshirt a perfect choice for anyone who values comfort. The embroidered “C” logo on the left sleeve will catch some eyes thanks to the world famous Champion brand.",
    "id": 5,
    "img_urlOne": "https://drive.google.com/uc?export=view&id=1F2nplNeLmhZzNuJuUQK0Ok_hK22wYUt1",
    "img_urlThree": "https://drive.google.com/uc?export=view&id=1F4NQ5CDTvKVJ6Cop1_Mq8UsdSJ34Q6TM",
    "img_urlTwo": "https://drive.google.com/uc?export=view&id=1F4nuYa3YWj41cwvJ6G0NJRt59zRMb0UC",
    "name": " DD-214 Alumni Champion Sweater",
    "price": 25,
    "amount": 1,
  },
  {
    "description": "The Richardson Snapback Trucker Cap has a classic structured fit, adjustable plastic snapback, and a curved visor that matches its underbill. Choose from several trendy colors, fine-tune your design, and add it to your headwear collection.",
    "id": 6,
    "img_urlOne": "https://drive.google.com/uc?export=view&id=1FELCKkgaiZTsIZnN5GLlsE6ri8FhbxOE",
    "img_urlThree": "https://drive.google.com/uc?export=view&id=1FRnb97D-ukJC8wbQdchckLspFzF0_eL9",
    "img_urlTwo": "https://drive.google.com/uc?export=view&id=1FL4moFOWyUfp5kNVNFKp5Mk1wyllPbGz",
    "name": " DD-214 Alumni Trucker Snap Back",
    "price": 20,
    "amount": 1,
  },
  {
    "description": "Say hello to our Stainless Steel Water Bottle made from high-grade stainless steel. Its double-wall construction makes it perfect for storing both hot and cold liquids. What’s better than taking that first sip of a coffee in the morning, or having a swig of icy-cold water after a workout? Enjoying your drinks from an easy-to-carry, beautifully designed, reusable bottle!",
    "id": 7,
    "img_urlOne": "https://drive.google.com/uc?export=view&id=1FrL1kQeSP3NIAFVC6CLVhHsw-Yy70I-P",
    "img_urlThree": "https://drive.google.com/uc?export=view&id=1FsNEml8ajTxzz7EkZ8DJj0Ymj9uw-FPF",
    "img_urlTwo": "https://drive.google.com/uc?export=view&id=1FricW6VDL-dzsj8EUipf5e7a0L3sIUqE",
    "name": " DD-214 Alumni Water Bottle",
    "price": 28,
    "amount": 1,
  },
  {
    "description": "100% polyester Knitted fabric Fabric weight: 4.42 oz/yd²(150 g/m²) Print on one side Blank reverse side Double-fold hem",
    "id": 8,
    "img_urlOne": "https://drive.google.com/uc?export=view&id=1FyjXn3K5INKPBCU_phqJBJxO2C0tq-P-",
    "img_urlThree": "https://drive.google.com/uc?export=view&id=1Fxy99iafZRJ1UB3lXl9FIsOcnvaRmLDM",
    "img_urlTwo": "https://drive.google.com/uc?export=view&id=1Fxy99iafZRJ1UB3lXl9FIsOcnvaRmLDM",
    "name": " DD-214 Alumni Flag",
    "price": 30,
    "amount": 1,
  },
  {
    "description": "Sturdy and sleek in glossy black—this mug is a cupboard essential for a morning java or afternoon tea",
    "id": 9,
    "img_urlOne": "https://drive.google.com/uc?export=view&id=1FzotIH9uxjrQGlLxn99bcFi2MWsqYD1P",
    "img_urlThree": "https://drive.google.com/uc?export=view&id=1FzcLmeqjy-vIb0gUgZOpDGACBfLfstYJ",
    "img_urlTwo": "https://drive.google.com/uc?export=view&id=1FzcLmeqjy-vIb0gUgZOpDGACBfLfstYJ",
    "name": "DD-214 Alumni Mug",
    "price": 20,
    "amount": 1,
  }
];

export default list;
